### ISSUE TITLE
Python type annotations cause analysis to fail

### ISSUE THREAD

**Issue by zgoda** [codeclimate/codeclimate-duplication#352]
```
I, [2019-10-22T16:03:19.340766 #1]  INFO -- : Skipping file ./src/bip/utils/text.py due to exception (CC::Engine::Analyzers::ParserError): `python2 /usr/src/app/lib/cc/engine/analyzers/python/parser.py` exited with code 1:
Traceback (most recent call last):
  File "/usr/src/app/lib/cc/engine/analyzers/python/parser.py", line 47, in <module>
    print(json.dumps(to_json(ast.parse(source))))
  File "/usr/local/python2/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 14
    def yesno(value: bool, capitalize: bool = True) -> str:
                   ^
SyntaxError: invalid syntax
```

**Comment by zgoda** [comment]
Sorry for the noise, I forgot to specify Python version in configuration file.
