### ISSUE TITLE
engine duplication failed with status 137

### ISSUE THREAD

**Issue by neseleznev** [codeclimate/codeclimate-duplication#369]
It's my first code climate run, and it's stuck on `duplication` engine.

```sh
>$ codeclimate analyze
```
gives
```
Starting analysis
Running structure: Done!
Running duplication: Done!
error: (CC::CLI::Analyze::EngineFailure) engine duplication failed with status 137 and stderr 
12
Parser process id: 12
codeclimate-parser socket not present
waiting 1s...
/home/app/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.0/lib/concurrent/atomic/mutex_atomic_fixnum.rb:80: warning: constant ::Fixnum is deprecated
/home/app/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.0/lib/concurrent/atomic/mutex_atomic_fixnum.rb:80: warning: constant ::Fixnum is deprecated
```

More details
```sh
>$ CODECLIMATE_DOCKER=1 CODECLIMATE_DEBUG=1 codeclimate analyze
```
Output:
```
D, [2022-01-14T10:10:42.378372 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `finished'
	/usr/src/app/lib/cc/analyzer/bridge.rb:52:in `block (2 levels) in run'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:63:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:31:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
	/usr/src/app/lib/cc/analyzer/bridge.rb:37:in `block in run'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `each'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:36:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
```

**Comment by neseleznev** [comment]
From `docker stats` I found that container consumed more that 1G memory, so I did
```sh
ENGINE_MEMORY_LIMIT_BYTES=2000000000 codeclimate analyze
```
and it, apparently, it did the fix. Now I'm stuck on failed PMD, but that's another story...

CLI output could be more friendly in case of OOM, WHYT @fede-moya ?
